// Hisab design tokens.
//
// Every value in this file is transcribed from the frontmatter of
//   _bmad-output/planning-artifacts/ux-designs/ux-hisab-dokan-2026-08-29/DESIGN.md
// which is the authority. Nothing here is invented, rounded or "improved". If a
// value needs to change, it changes in DESIGN.md first and is copied down here;
// test/theme/tokens_test.dart asserts both the values and the group sizes so a
// silent drift fails the build.
//
// This file deliberately contains NO ThemeData and no widgets — it is one flat
// list you can hold beside the design document and diff by eye.
//
// Everything outside lib/theme/ reads style from Theme.of(context) or from these
// constants. tool/check_theme_tokens.dart enforces that.

import 'package:flutter/material.dart';

/// The fifteen colour tokens. DESIGN.md § Colors.
///
/// `accent` and `moneyIn` deliberately share one value: "one colour doing two
/// jobs that never conflict — primary actions, and money coming in". They are
/// two names because a later change to one must not silently change the other.
///
/// Colour carries exactly one meaning each — in, out, warning, AI — and never
/// decorates.
abstract final class HisabColors {
  /// The ground, everywhere. Warm enough to read as paper.
  static const Color paper = Color(0xFFFAF5EA);

  /// Recessed bands: table headers, chips, the strip under an app bar.
  /// The only second surface; there is no third.
  static const Color paperSunk = Color(0xFFF1E7D3);

  /// What cards and rows sit on — a shade lighter than paper, so a card lifts
  /// by tone rather than by shadow.
  static const Color surface = Color(0xFFFFFDF8);

  /// Every line in the product. One weight, one colour, everywhere.
  static const Color rule = Color(0xFFE4D9C2);

  /// Text and, above all, money. Warm near-black, never pure black.
  static const Color ink = Color(0xFF2B2419);

  /// Labels, timestamps, secondary lines.
  static const Color inkMuted = Color(0xFF7C6F5B);

  /// Placeholder text only.
  static const Color inkFaint = Color(0xFFB9AC94);

  /// Primary actions. A deep ledger green, ink-like rather than brand-like.
  static const Color accent = Color(0xFF1F5D46);

  /// Money coming in. Same value as [accent], by design.
  static const Color moneyIn = Color(0xFF1F5D46);

  /// Dues owed, money leaving, destructive actions. Terracotta.
  /// The strongest red the product owns — there are no red error fills.
  static const Color moneyOut = Color(0xFF9C4221);

  /// Reserved almost entirely for stock and for disclosures the owner must read.
  static const Color warn = Color(0xFF8A6516);
  static const Color warnSurface = Color(0xFFF6EAD2);
  static const Color warnRule = Color(0xFFE3CFA4);

  /// Marks something generated by Hisab rather than recorded by the owner.
  static const Color aiSurface = Color(0xFFEBF1EC);
  static const Color aiRule = Color(0xFFC9DCCE);

  /// Keyed by the DESIGN.md frontmatter names, for the drift test and for
  /// the palette section of the preview screen.
  static const Map<String, Color> all = <String, Color>{
    'paper': paper,
    'paper-sunk': paperSunk,
    'surface': surface,
    'rule': rule,
    'ink': ink,
    'ink-muted': inkMuted,
    'ink-faint': inkFaint,
    'accent': accent,
    'money-in': moneyIn,
    'money-out': moneyOut,
    'warn': warn,
    'warn-surface': warnSurface,
    'warn-rule': warnRule,
    'ai-surface': aiSurface,
    'ai-rule': aiRule,
  };
}

/// The two bundled families. DESIGN.md § Typography, UX-DR3.
///
/// Both ship as app assets (see `assets/fonts/`, declared in pubspec.yaml).
/// Neither is ever requested at runtime: the app renders correctly with no
/// connection, and the same faces have to work inside a generated PDF receipt.
abstract final class HisabFonts {
  /// Ledger headings, screen titles, receipts. Never body copy, never below
  /// [displayMinSize].
  static const String display = 'NotoSerifBengali';

  /// Everything else, including every number.
  static const String ui = 'HindSiliguri';

  /// Only reached if a bundled face fails to load — which is a build defect,
  /// not a runtime condition. Present so a broken build is legible enough to
  /// diagnose, not so it is shippable.
  static const List<String> displayFallback = <String>['Georgia', 'serif'];
  static const List<String> uiFallback = <String>['system-ui', 'sans-serif'];

  /// "It never sets body copy and never appears below 17px."
  static const double displayMinSize = 17;
}

/// One entry in the type scale. DESIGN.md § typography.scale.
@immutable
class HisabTypeRole {
  const HisabTypeRole({
    required this.name,
    required this.family,
    required this.size,
    required this.weight,
    this.letterSpacing,
    this.color,
  });

  /// The DESIGN.md frontmatter key, e.g. `amount-xl`.
  final String name;
  final String family;
  final double size;
  final FontWeight weight;
  final double? letterSpacing;

  /// Set only where DESIGN.md fixes a colour on the role itself.
  final Color? color;

  /// True for the roles that set money. Money is the largest thing on any
  /// screen it appears on.
  bool get isAmount => name.startsWith('amount-');
}

/// The eight type roles: four amount sizes and four text roles.
///
/// The scale is short on purpose. There are no display sizes above `amount-xl`
/// and no all-caps labels except the ledger table header.
abstract final class HisabTypeScale {
  /// 36px / 700 / -0.02em. The hero figure.
  static const HisabTypeRole amountXl = HisabTypeRole(
    name: 'amount-xl',
    family: HisabFonts.ui,
    size: 36,
    weight: FontWeight.w700,
    // -0.02em at 36px. DESIGN.md states the tracking in em; Flutter's
    // letterSpacing is logical pixels, so it is resolved here once.
    letterSpacing: -0.72,
  );

  /// 26px / 700. Also the size an amount field rises to while being entered.
  static const HisabTypeRole amountLg = HisabTypeRole(
    name: 'amount-lg',
    family: HisabFonts.ui,
    size: 26,
    weight: FontWeight.w700,
  );

  /// 19px / 700.
  static const HisabTypeRole amountMd = HisabTypeRole(
    name: 'amount-md',
    family: HisabFonts.ui,
    size: 19,
    weight: FontWeight.w700,
  );

  /// 15px / 700. The running-balance column in a ledger row.
  static const HisabTypeRole amountSm = HisabTypeRole(
    name: 'amount-sm',
    family: HisabFonts.ui,
    size: 15,
    weight: FontWeight.w700,
  );

  /// 18px / 600 / display family. Screen titles and ledger headings.
  static const HisabTypeRole title = HisabTypeRole(
    name: 'title',
    family: HisabFonts.display,
    size: 18,
    weight: FontWeight.w600,
  );

  /// 15px / 400.
  static const HisabTypeRole body = HisabTypeRole(
    name: 'body',
    family: HisabFonts.ui,
    size: 15,
    weight: FontWeight.w400,
  );

  /// 12px / 500 / ink-muted.
  static const HisabTypeRole label = HisabTypeRole(
    name: 'label',
    family: HisabFonts.ui,
    size: 12,
    weight: FontWeight.w500,
    color: HisabColors.inkMuted,
  );

  /// 12.5px / 400 / ink-muted.
  static const HisabTypeRole meta = HisabTypeRole(
    name: 'meta',
    family: HisabFonts.ui,
    size: 12.5,
    weight: FontWeight.w400,
    color: HisabColors.inkMuted,
  );

  static const Map<String, HisabTypeRole> all = <String, HisabTypeRole>{
    'amount-xl': amountXl,
    'amount-lg': amountLg,
    'amount-md': amountMd,
    'amount-sm': amountSm,
    'title': title,
    'body': body,
    'label': label,
    'meta': meta,
  };

  /// The amount ramp, largest first.
  static const List<HisabTypeRole> amounts = <HisabTypeRole>[
    amountXl,
    amountLg,
    amountMd,
    amountSm,
  ];

  /// The four text roles.
  static const List<HisabTypeRole> text = <HisabTypeRole>[
    title,
    body,
    label,
    meta,
  ];
}

/// The five radii. DESIGN.md § rounded / § Shapes.
abstract final class HisabRadii {
  /// Receipts, the deliberate outlier: a receipt reads as a printed slip.
  static const double sm = 6;

  /// Fully round. Chips only.
  static const double chip = 999;

  /// Fields and banners.
  static const double md = 12;

  /// Cards and quick actions.
  static const double lg = 14;

  /// The top corners of a bottom sheet.
  static const double sheet = 20;

  static const Map<String, double> all = <String, double>{
    'sm': sm,
    'chip': chip,
    'md': md,
    'lg': lg,
    'sheet': sheet,
  };
}

/// The six-step spacing scale: 4 / 8 / 12 / 16 / 22 / 32.
abstract final class HisabSpacing {
  /// Between a label and its value.
  static const double s1 = 4;
  static const double s2 = 8;

  /// Between stacked cards.
  static const double s3 = 12;

  /// Screen margin.
  static const double s4 = 16;
  static const double s5 = 22;
  static const double s6 = 32;

  static const Map<String, double> all = <String, double>{
    '1': s1,
    '2': s2,
    '3': s3,
    '4': s4,
    '5': s5,
    '6': s6,
  };

  /// Screen margin is 16. DESIGN.md § Layout & Spacing.
  static const double screenMargin = s4;

  /// Gaps between stacked cards are 12.
  static const double cardGap = s3;
}

/// Component metrics that DESIGN.md § components fixes but that are not part of
/// the colour / type / radius / spacing groups above.
abstract final class HisabMetrics {
  /// One line weight for every rule in the product.
  static const double ruleWidth = 1;

  /// The accessibility floor, everywhere (UX-DR21).
  static const double minHitTarget = 48;

  // Buttons: three levels only, all 54px / radius 13.
  static const double buttonHeight = 54;
  static const double buttonRadius = 13;
  static const double buttonLabelSize = 16.5;
  static const FontWeight buttonLabelWeight = FontWeight.w600;

  /// Secondary buttons are an accent outline, 1.5px.
  static const double buttonBorderWidth = 1.5;

  // Quick actions: the highest-traffic component. Three across, icon over label.
  static const double quickActionMinHeight = 80;
  static const double quickActionIconSize = 24;
  static const double quickActionLabelSize = 13.5;
  static const FontWeight quickActionLabelWeight = FontWeight.w600;

  // Fields: label above value, the value large because the owner checks the
  // number they just typed while a customer watches.
  static const double fieldPaddingVertical = 11;
  static const double fieldPaddingHorizontal = 13;
  static const double fieldLabelSize = 12;
  static const double fieldValueSize = 17;
  static const FontWeight fieldValueWeight = FontWeight.w600;

  // Chips.
  static const double chipPaddingVertical = 5;
  static const double chipPaddingHorizontal = 11;
  static const double chipLabelSize = 12;
  static const FontWeight chipLabelWeight = FontWeight.w600;

  /// Cards are 14 inside.
  static const double cardPadding = 14;

  // Ledger row: grid 52px | 1fr | 78px | 82px, 11/16 padding, 13px text.
  // The component everything else serves.
  static const double ledgerDateWidth = 52;
  static const double ledgerAmountWidth = 78;
  static const double ledgerBalanceWidth = 82;
  static const double ledgerPaddingVertical = 11;
  static const double ledgerPaddingHorizontal = 16;
  static const double ledgerTextSize = 13;

  /// Fixed, 58px, 1px rule below.
  static const double appBarHeight = 58;

  /// 66px, surface fill, 1px rule above, icon 21 over label 11.
  static const double bottomNavHeight = 66;
  static const double bottomNavIconSize = 21;
  static const double bottomNavLabelSize = 11;

  /// Disclosure banner and AI surface text size.
  static const double bannerTextSize = 13;

  /// Icons are line drawings on a 24px grid.
  static const double iconSize = 24;

  /// Elevation is effectively none: cards separate by tone and a 1px rule.
  /// The only two exceptions in the whole product are a bottom sheet and the
  /// centre navigation button, and neither exists yet.
  static const double flat = 0;
}
